### PR TITLE
Added Nodejs support

### PR DESCRIPTION
**Pull request by rudzon**
Done in style like in java version. Should work, didn't test it well actually. Have fun

### CODE REVIEW

**Comment by AlexeySpiridonov** [comment]
погляди правки, ничего не поломал?

**Comment by rudzon** [comment]
×ÒÏÄÅ ÎÅÁ

On Thu, Jan 16, 2014 at 9:38 AM, Alexey Spiridonov <notifications@github.com

**Comment by AlexeySpiridonov** [comment]
абракадабра какая то :)

**Comment by rudzon** [comment]
=)

**Pull request merged**
